source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'YTXTest_Example', :exclusive => true do
  pod 'YTXTest', :path => '../'
end

target 'YTXTest_Tests', :exclusive => true do
  pod 'YTXTest', :path => '../'

  pod 'Kiwi'
end
